### ISSUE TITLE
Broken rss feed

### ISSUE THREAD

**Issue by duarteocarmo** [ericmjl/website#45]
Hey Eric!

Long time fan of your work!

Just wanted to let you know that your rss feed seems broken. 

If we go to the [rss link](https://ericmjl.github.io/blog.xml), all of your articles appear as:

```xml
...
<entry xml:base="http://www.ericmjl.com/blog/2021/5/19/grammarly-is-surprisingly-useful/">
<title type="text">Grammarly is surprisingly useful</title>
...
```

But your blog seems to be hosted in `https://ericmjl.github.io` (instead of `http://www.ericmjl.com`), so all links in your rss return a "Server not found error". 

Love following your blog via rss, so that's why I noticed 😄 

Have a great day, and keep writing great content!

**Comment by ericmjl** [comment]
@duarteocarmo thank you for finding the bug with my blog and reporting it! I am going to see if I can fix the atom feed in my website's config.

**Comment by ericmjl** [comment]
@duarteocarmo I think I've fixed the bug. Please let me know if it's still an issue!

**Comment by duarteocarmo** [comment]
Seems to be fixed now, at least in the rss feed! I'll let you know once my rss feed refreshes if there are any problems 😄 

Keep writing great content @ericmjl, we all appreciate it 🚀
